### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by AdjectiveAllison** [zml/zml#118]
### The [API Docs](https://docs.zml.ai/misc/zml_api/) section of the website

It would be nice if this is more easily extractable for use with llms.
I can get all the other markdown pages from the github repo but since these are auto generated I guess they aren't in the repo anywhere? 
One nice thing about [the zig documentation](https://ziglang.org/documentation/0.13.0/) is that it's a single page, so I can easily convert the entire docs from html to markdown with one command and use for context. 

It looks like the zml_api page specifically isn't working well with my HTML->Markdown processor anyway currently (even if I try to run each section through). The content may be dynamically rendered? It says `Loading...` and has empty code blocks and headers when I run it through. The same process works well for the other doc pages on `docs.zml.ai` (the ones mapped to the primary repos docs directory)

One alternative, potential route is doing something similar to the [llms.txt](https://llmstxt.org) proposition, where the docs can be accessed in a text(md) format by themselves. Then I don't even have to grab raw markdown from the repo nor do conversions. 

### Command line options / Debugging

What is the full list of command line options? How do I do logging/debugging? What if I want to adjust cuda allocation size (This is a real question specifically if you just want to answer this)? 

Not the most urgent, but would be a nice to have.

**Comment by renerocksai** [comment]
You are correct, the API docs are generated in the browser, just like the [Zig Standard Library Documentation](https://ziglang.org/documentation/master/std/), via ["autodoc"](https://github.com/ziglang/zig/tree/master/lib/docs). It's pretty cool zig code -> wasm that live-renders interlinked API docs directly from zig sources inside a tar file.

It seems like it got spun off into its own [docgen project](https://github.com/ziglang/docgen).

So, I guess, we'll have to split the issue into multiple: 

- ZML API docs offline mode (not sure how that can be done yet) - might even be a thing for the [docgen](https://github.com/ziglang/docgen) project.
- command line options : I think you mean for bazel-building?

**Comment by AdjectiveAllison** [comment]
Ahhh, very interesting info on the docgen (and cool indeed!).

And yes, command line options for bazel-building.

**Comment by AdjectiveAllison** [comment]
It looks like the documentation you're using is still autodoc. docgen is a different project for offline html templating and doc generation that's used [here](https://ziglang.org/documentation/0.13.0/), but it doesn't seem zml is doing anything with it. I'll close this, as after some research based on the resources you gave me, it seems there aren't any reasonably accessible ways to do what I'm asking for the api docs. I have some javascript code I can use to extract them in the browser if I want to in the mean time. I'll open up another issue with more specific and accurate details of what I'm asking for on the bazel build arguments.

**Comment by renerocksai** [comment]
You're right, we're using the good old autodoc from the zig compiler source tree. We talked about this and one idea was: the zig code that's being put in the wasm already contains everything to go from a type name to nicely formatted HTML. So it should be possible to iterate over "all" types and call the HTML-formatting thing, and write to disk instead of doing it in a webserver; basically producing a statically-generated HTML tree.
